#pragma once
#include "KhaosStdTypes.h"

namespace Khaos
{
#define KHAOS_DECL_STR_NAME_(x) extern const String x

    KHAOS_DECL_STR_NAME_(STRING_EMPTY);

    // shader uniform
    KHAOS_DECL_STR_NAME_(NAME_SURFACE_PARAMS);
    KHAOS_DECL_STR_NAME_(NAME_SPECULARMASK_PARAMS);
    KHAOS_DECL_STR_NAME_(NAME_MTR_ALPHAREF);

    //KHAOS_DECL_STR_NAME_(NAME_MTR_DIFFUSEA);
    //KHAOS_DECL_STR_NAME_(NAME_MTR_SPECULAR);
    //KHAOS_DECL_STR_NAME_(NAME_MTR_EMISSIVE);

    KHAOS_DECL_STR_NAME_(NAME_MAP_BASE);
    KHAOS_DECL_STR_NAME_(NAME_MAP_SPECULAR);
    KHAOS_DECL_STR_NAME_(NAME_MAP_EMISSIVE);
    KHAOS_DECL_STR_NAME_(NAME_MAP_BUMP);
    KHAOS_DECL_STR_NAME_(NAME_MAP_OPACITY);
    KHAOS_DECL_STR_NAME_(NAME_MAP_BAKEDAO);

    //KHAOS_DECL_STR_NAME_(NAME_MAP_DIFFUSE);

    KHAOS_DECL_STR_NAME_(NAME_MAP_LIGHT);
    KHAOS_DECL_STR_NAME_(NAME_MAP_LIGHTB);
    KHAOS_DECL_STR_NAME_(NAME_MAP_VOLR);
    KHAOS_DECL_STR_NAME_(NAME_MAP_VOLG);
    KHAOS_DECL_STR_NAME_(NAME_MAP_VOLB);

    KHAOS_DECL_STR_NAME_(NAME_MAP_ENVDIFF);
    KHAOS_DECL_STR_NAME_(NAME_MAP_ENVSPEC);
    KHAOS_DECL_STR_NAME_(NAME_ENVMAPINFOA);

    KHAOS_DECL_STR_NAME_(NAME_AMBPARAS);
    KHAOS_DECL_STR_NAME_(NAME_DIRLITS);
    KHAOS_DECL_STR_NAME_(NAME_POINTLITS);
    KHAOS_DECL_STR_NAME_(NAME_SPOTLITS);
    KHAOS_DECL_STR_NAME_(NAME_DIRLITS_COUNT);
    KHAOS_DECL_STR_NAME_(NAME_POINTLITS_COUNT);
    KHAOS_DECL_STR_NAME_(NAME_SPOTLITS_COUNT);

    KHAOS_DECL_STR_NAME_(NAME_MATSHADOWPROJ);
    KHAOS_DECL_STR_NAME_(NAME_SHADOWPARAMS);
    KHAOS_DECL_STR_NAME_(NAME_MAPSHADOW0);
    KHAOS_DECL_STR_NAME_(NAME_MAPSHADOW1);
    KHAOS_DECL_STR_NAME_(NAME_MAPSHADOW2);
    KHAOS_DECL_STR_NAME_(NAME_MAPSHADOW3);

    KHAOS_DECL_STR_NAME_(NAME_MATWORLD);
    KHAOS_DECL_STR_NAME_(NAME_MATWORLDVIEW);
    KHAOS_DECL_STR_NAME_(NAME_MATWVP);
    KHAOS_DECL_STR_NAME_(NAME_MATPROJINV);
    KHAOS_DECL_STR_NAME_(NAME_MATVIEWPROJINV);
    KHAOS_DECL_STR_NAME_(NAME_MATVIEWTOTEX);
    KHAOS_DECL_STR_NAME_(NAME_MATWORLDTOVOL);

    KHAOS_DECL_STR_NAME_(NAME_CAMERAPOSWORLD);
    KHAOS_DECL_STR_NAME_(NAME_CAMERAZFAR);
    KHAOS_DECL_STR_NAME_(NAME_CAMERAZFARFOV);
    KHAOS_DECL_STR_NAME_(NAME_CAMERAINFO);
    KHAOS_DECL_STR_NAME_(NAME_TARGETINFO);
    KHAOS_DECL_STR_NAME_(NAME_TARGETINFOEX);
    KHAOS_DECL_STR_NAME_(NAME_SCREENSCALE);

    KHAOS_DECL_STR_NAME_(NAME_POISSON_DISK);
    KHAOS_DECL_STR_NAME_(NAME_RANDOM_REPEAT);
    KHAOS_DECL_STR_NAME_(NAME_MAP_RANDOM);
    KHAOS_DECL_STR_NAME_(NAME_MAP_NORMALFITTING);
    KHAOS_DECL_STR_NAME_(NAME_MAP_ENVLUT);
    
    KHAOS_DECL_STR_NAME_(NAME_GBUF_DIFFUSE);
    KHAOS_DECL_STR_NAME_(NAME_GBUF_SPECULAR);
    KHAOS_DECL_STR_NAME_(NAME_MAP_DEPTH);
    KHAOS_DECL_STR_NAME_(NAME_MAP_DEPTHHALF);
    KHAOS_DECL_STR_NAME_(NAME_MAP_DEPTHQUARTER);
    KHAOS_DECL_STR_NAME_(NAME_MAP_NORMAL);
    KHAOS_DECL_STR_NAME_(NAME_MAP_AO);
    KHAOS_DECL_STR_NAME_(NAME_MAP_INPUT);

    KHAOS_DECL_STR_NAME_(NAME_SSAO_PARAMS);
    KHAOS_DECL_STR_NAME_(NAME_SSAO_SAMPLE_KERNELS);
    KHAOS_DECL_STR_NAME_(NAME_FILTER_SAMPLE_OFFSETS);
    KHAOS_DECL_STR_NAME_(NAME_FILTER_INFO);

    KHAOS_DECL_STR_NAME_(NAME_GAMMA_VALUE);

    KHAOS_DECL_STR_NAME_(NAME_CALCLUM_PARAMS);

    KHAOS_DECL_STR_NAME_(NAME_DOWNSCALEZ_PARAMA);
    KHAOS_DECL_STR_NAME_(NAME_DOWNSCALEZ_PARAMB);

    KHAOS_DECL_STR_NAME_(NAME_COMM_PARAMA);
    KHAOS_DECL_STR_NAME_(NAME_COMM_PARAMB);
    KHAOS_DECL_STR_NAME_(NAME_COMM_PARAMC);

    KHAOS_DECL_STR_NAME_(NAME_MAP_LUM0);
    KHAOS_DECL_STR_NAME_(NAME_MAP_LUM1);
    KHAOS_DECL_STR_NAME_(NAME_MAP_TARGETFULL);
    KHAOS_DECL_STR_NAME_(NAME_MAP_TARGETQUARTER);
    KHAOS_DECL_STR_NAME_(NAME_MAP_TARGETEIGHTH);
    KHAOS_DECL_STR_NAME_(NAME_MAP_TARGETSIXTEENTH);

    KHAOS_DECL_STR_NAME_(NAME_HDRParams0);
    KHAOS_DECL_STR_NAME_(NAME_HDRParams1);
    KHAOS_DECL_STR_NAME_(NAME_HDRParams5);
    KHAOS_DECL_STR_NAME_(NAME_HDRParams8);

    KHAOS_DECL_STR_NAME_(NAME_MAP_AREA);
    KHAOS_DECL_STR_NAME_(NAME_MAP_SEARCH);
    KHAOS_DECL_STR_NAME_(NAME_MAP_COLOR);
    KHAOS_DECL_STR_NAME_(NAME_MAP_BLEND);

    KHAOS_DECL_STR_NAME_(NAME_MAP_FRAMECURR);
    KHAOS_DECL_STR_NAME_(NAME_MAP_FRAMEPRE);
    KHAOS_DECL_STR_NAME_(NAME_MATVIEWPROJPRE);

    KHAOS_DECL_STR_NAME_(NAME_JITTER_WORLD);
    KHAOS_DECL_STR_NAME_(NAME_JITTER_UV);

    KHAOS_DECL_STR_NAME_(NAME_CAMVOLBIAS);

    KHAOS_DECL_STR_NAME_(NAME_COMMSCALE_PARAMS);
    KHAOS_DECL_STR_NAME_(NAME_COMMBLUR_TEXOFFSETS);
    KHAOS_DECL_STR_NAME_(NAME_COMMBLUR_PSWEIGHTS);
}

